server {
    listen 3000;
    listen [::]:3000;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        # 字体资源需允许跨域加载
        add_header Access-Control-Allow-Origin *;
        try_files $uri $uri.html $uri/index.html =404;
    }

    error_page 404 /404.html;
}
